Fix integration tests (#1198)
Integration test caught some bugs!

1. From https://github.com/firebase/firebase-functions/pull/1155 - Some internal type must be exposed - otherwise compiling user projects fails w/ error message like below:

```
Error: node_modules/firebase-functions/lib/common/params.d.ts(10,13): error TS2314: Generic type 'Extract' requires 2 type argument(s).
Error: node_modules/firebase-functions/lib/common/params.d.ts(10,21): error TS2304: Cannot find name 'Split'.
Error: node_modules/firebase-functions/lib/common/params.d.ts(10,27): error TS2304: Cannot find name 'NullSafe'.
```

2. From https://github.com/firebase/firebase-functions/pull/1181 - There is no way to call private callable functions since GCF requrie GCP identity token as authorization header while callable function requires Firebase auth tokens. Disabling those test cases in the integration test until we can mint a GCP project w/ permission to create public functions.