Fix release script. (#1602)
* Fix release script.

Today, release script is broken with error message:

```
node_modules/google-gax/build/src/fallback.d.ts:20:34 - error TS2724: '"google-auth-library"' has no exported member named 'AnyAuthClient'. Did you mean 'AuthClient'?

20 import { GoogleAuth, AuthClient, AnyAuthClient } from 'google-auth-library';
```

It looks like the issue is related to some odd type incompatibility issue in an upstream package (google-gax). Rather than wait for the issue to be resolved, the change here removes command to install firebase-admin which isn't needed to build the release package anyway.

* Revert change to remove --production flag.