BREAKING: Break TS build that uses functions.config() (#1757)
Type out `functions.config()` API. Use of `functions.config()` API should now cause a BUILD error at compile time.

```ts
import * as functions from "firebase-functions";
import {onRequest} from "firebase-functions/https";
import * as logger from "firebase-functions/logger";

const cfg = functions.config()

export const helloWorld = onRequest((request, response) => {
  logger.info("Hello logs!", cfg);
  response.send("Hello from Firebase!");
});
```
```bash
$ npm run build

> build
> tsc

src/index.ts:5:23 - error TS2349: This expression is not callable.
  Type 'never' has no call signatures.

5 const cfg = functions.config()
                        ~~~~~~


Found 1 error in src/index.ts:5
```